import localFont from "next/font/local";
import "./globals.css";
import Header from "./_components/Header/header";
import Footer from "./_components/Footer/footer";
import { Roboto } from 'next/font/google'

const roboto = Roboto({
  weight: '400',
  subsets: ['latin'],
  display: 'swap'

})


export const metadata = {
  // title: "Mern next app",
  title: {
    template: "%s Mern next app",
    default: "Mern next app"
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const path = typeof window !== "undefined" ? window.location.pathname : "";
  const isLoginPage = path === "/login";

  return (
    <html lang="en">
      <body
        className={roboto}
      >
        {!isLoginPage && <Header />}
        <div style={{}}>
          {children}
        </div>
        {!isLoginPage && <Footer />}
      </body>
    </html>
  );
}
